#!/bin/bash
export JAVA_HOME="/c/Program Files/Java/jdk-12.0.2/bin"
source $(dirname $0)/.env
export JAVA=$JAVA_HOME/java
echo $0
#"$JAVA" -jar ../../build/lib/ant-launcher.jar -f sandbox-util/update-repo.ant.xml
"$JAVA" -jar ../../build/lib/ant-launcher.jar
$0/test

